<?php

/**
 * @file
 * Adds javascript libraries and javascript to nodes.
 */

use Drupal\Core\Form\FormStateInterface;
use Drupal\Core\Entity\Node;
use Drupal\Core\Entity\Display\EntityViewDisplayInterface;
use Drupal\Core\Entity\EntityInterface;

/**
 * Implements hook_entity_view()
 */
function media_share_entity_view(array &$build, \Drupal\Core\Entity\EntityInterface $entity, \Drupal\Core\Entity\Display\EntityViewDisplayInterface $display, $view_mode) {
  if($entity->getEntityTypeId() ==  "node"){
    $build['#attached']['library'][] = 'media_share/media-share';
    $build['#attached']['library'][] = 'media_share/media-share-init';
    $config = \Drupal::service('config.factory')->getEditable('media_share.settings');
    $elements = $config->get('custom_elements');
    $build['#attached']['html_head'][] = [
      [
        '#type' => 'html_tag',
        '#tag' => 'script',
        '#value' => "window.onload = function(e){jQuery('".$elements."').sti({primary_menu: ['facebook', 'twitter', 'google', 'pinterest']});}",
      ],
      'custom-elements'
    ];
  }
}
